# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webappcustomer1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://monsoonwebappreg.azurecr.io/
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_206BA2C2D0054251BE245DC3A06061B7 }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_FC668BF22ECC46B08A65255C46C7F609 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: monsoonwebappreg.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_206BA2C2D0054251BE245DC3A06061B7 }}/monsoonwebapp_client:${{ github.sha }}
        file: ./Client/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webappcustomer1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CC9458A0931D4A5BA8D85F3F8EDD14DB }}
        images: 'monsoonwebappreg.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_206BA2C2D0054251BE245DC3A06061B7 }}/monsoonwebapp_client:${{ github.sha }}'